config/routes.rb
Rails.application.routes.draw do

  get 'timeslots/index'
  get 'timeslots/new'
  post 'timeslots/create'
  get 'teacher/index'
  get 'teacher/show'
  get 'teacher/new'
  get 'student/index'
  get 'student/show'
  get 'admin/show'
  namespace :admin do
    resources :students, only: [:new, :edit, :create, :destroy, :update, :index]
    resources :calendar, only: [:new, :edit, :create, :destroy, :update]
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :static_pages
  root to: "static_pages#home"

  resources :lesson, only: [:create, :destroy]
  resources :calendar, only: [:index, :create, :new, :show]
  get 'home', to: 'static_pages#home'
  get 'accueille', to: 'static_pages#accueille'
  get 'permis_auto', to: 'static_pages#permis_auto'
  get 'permis_moto', to: 'static_pages#permis_moto'
  get 'contact', to: 'static_pages#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_many :timeslots
  belongs_to :teacher

  accepts_nested_attributes_for :timeslots
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :student
  belongs_to :timeslot
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :lessons

  has_many :timeslots, through: :lessons
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :calendars
  has_many :timeslots
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  belongs_to :teacher
  belongs_to :calendar
  has_many :time_slots
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_one :student
  has_one :teacher

  accepts_nested_attributes_for :student
  accepts_nested_attributes_for :teacher
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_action :check_teacher, except: [:index, :show]

  def index
    @calendar_all = Calendar.where("reference_day >= ?", Date.today)
  end

  def show
    @lessons = Lesson.all
    @calendar_selected = Calendar.find(params[:id])
  end

  def new
    @calendar = Calendar.new
  end

  def create
    (0..end_date_loop).each do |i|
      iterated_day = start_date_selected + i
      calendar = Calendar.new(:teacher_id => current_user.teacher.id,
      :reference_day => iterated_day)
      calendar.save
    end
    redirect_to calendar_index_path
  end

  private
  def check_teacher
    unless current_user.teacher != nil || current_user.admin == true
      redirect_to '/', :alert => "Don't have permission!"
    end
  end

  def end_date_loop
    (end_date_selected - start_date_selected).to_i
  end

  def start_date_selected
    Date.strptime(custom_params.values[0..2].join('-'), "%d-%m-%Y")
  end

  def end_date_selected
    Date.strptime(custom_params.values[3..5].join('-'), "%d-%m-%Y")
  end

  def custom_params
    params.require(:calendar).permit(:start_date, :end_date)
  end

end

app/controllers/lesson_controller.rb
class LessonController < ApplicationController

  def show
  end

  def create
    create_lesson = Lesson.new(student_id: current_user.student.id, timeslot_id: params[:timeslot_id])
    if current_user.student.credits == nil || current_user.student.credits < 1
      flash[:erreur] = "Erreur, vous n'avez pas assez des credits pour le créneau !"
      redirect_to calendar_index_path
    elsif create_lesson.save
      current_user.student.update({credits: current_user.student.credits-1})
      redirect_to student_show_path
    else
      flash["error"] = "Vous n'avez pas crée la lesson"
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    if @lesson.destroy
      current_user.student.update({credits: current_user.student.credits+1})
      redirect_to student_show_path
    end
  end

  private

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    render layout: false
  end

  def accueille
  end

  def permis_auto
  end

  def permis_moto
  end

  def contact
  end

end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :configure_sign_up_params, only: [:create]
  before_action :check_student, except: [:index]

  def index
    @students = Student.all
  end

  def show
    @current_student = current_user.student
    @lesson = Lesson.where(student_id: current_user.student.id)
  end

  private
  def check_student
    unless current_user.student || current_user.admin == true
        redirect_to '/', :alert => "Don't have permission!"
    end
  end

end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController

  def show
    @current_teacher = current_user.teacher
  end

end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  before_action :check_teacher, except: [:index]

  def index
    @time_slots_all = Timeslot.all
    @calendar_week_day = Calendar.all
    #Timeslot.find(:all, :conditions => [@time_slots_all.start_slot < Time.now])
  end

  def new
    @time_slots = Timeslot.new
  end

  def create
      Calendar.all.each do |calendar|
      day = calendar.reference_day.strftime('%A')
      if day == "Monday"
        (0..length1).each do |x|
          final_slots = Timeslot.new(teacher_id: current_user.teacher.id,
          start_slot: looping_slots(morning_start + (4 * 3600 ))[x],
          end_slot: looping_slots(morning_start + (5 * 3600))[x],
          calendar_id: calendar.id
          )
          final_slots.save
        end
      elsif day == "Tuesday" || day == "Wednesday" || day == "Friday" || day == "Thursday"
        (0..length2).each do |x|
          final_slots = Timeslot.new(teacher_id: current_user.teacher.id,
          start_slot: loop_full_day(morning_start)[x],
          end_slot: loop_full_day(morning_start + 3600)[x],
          calendar_id: calendar.id
          )
          final_slots.save
        end
      elsif day == "Saturday"
        (0..length1).each do |x|
          final_slots = Timeslot.new(teacher_id: current_user.teacher.id,
          start_slot: looping_slots(morning_start)[x],
          end_slot: looping_slots(morning_start + 3600)[x],
          calendar_id: calendar.id
          )
          final_slots.save
        end
      end
    end
  end

  private
  def check_teacher
    unless current_user.teacher
        redirect_to '/', :alert => "Don't have permission!"
    end
  end

  def length1
    looping_slots(morning_start + (4 * 3600)).length - 1
  end

  def length2
    loop_full_day(morning_start).length - 1
  end

  def looping_slots(slot)
    (0..4).map do |i|
      (slot + i * 3600).hour.to_s
    end
  end

  def loop_full_day(slot)
    [0,1,2,3,4,6,7,8,9].map do |i|
      (slot + (i * 3600)).hour.to_s
    end
  end

  def morning_start
    Time.parse("08:00")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lesson_helper.rb
module LessonHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/teacher_student_helper.rb
module TeacherStudentHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/static_pages/accueille.html.erb
<!DOCTYPE html>

<div style="width: 580px; margin: 0 auto; padding-top: 55px; padding-bottom: 80px;">
  <div class="testimonial-quote group">
    <div class="quote-container">
      <blockquote>
        <p>Bienvenue dans notre page ... et ...</p>
      </blockquote>
    </div>
  </div>
</div>

<div class="wrapper1">
  <div class="wrapper1-item">
    <%= image_tag "reunion-voit.jpg", height: 275, width: 600 %>
  </div>
  <div class="wrapper1-item">
    <p>
      If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the
      middle of text. All the Lorem Ipsum generators on the. Internet tend to repeat predefined chunks as necessary, making this
      the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model
      sentence structures, to generate Lorem Ipsum which looks reasonable.
    </p>
  </div>
</div>

<div style="width: 600px; margin: 0 auto; padding-top: 80px; padding-bottom: 60px;">
  <div class="testimonial-quote group">
    <div class="quote-container">
      <blockquote>
        <p>Statistiques reussite, phrase de pub. ― @nom prenom</p>
      </blockquote>
    </div>
  </div>
</div>

<div class="wrapper2">
  <div class="wrapper2-item">
    <p>
      If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the
      middle of text. All the Lorem Ipsum generators on the. Internet tend to repeat predefined chunks as necessary, making this
      the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model
      sentence structures, to generate Lorem Ipsum which looks reasonable.
    </p>
  </div>
  <div class="wrapper2-item">
    <%= image_tag "reunion-voit.jpg", height: 275, width: 600 %>
  </div>
</div>

<div style="width: 960px; margin: 0 auto; padding-top: 80px; padding-bottom: 80px;">
  <div class="testimonial-quote group">
    <div class="quote-container">
      <blockquote>
        <p>Ajouttons des autres informations clés!</p>
      </blockquote>
    </div>
  </div>
</div>

app/views/static_pages/contact.html.erb
<!DOCTYPE html>
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
</head>
  <h3> Nous contacter </h3>
  <div class="general-body">
    <div class="contact-page">
      <div class="contact-info">
        <div class="item">
          <i class="icon fas fa-home center"></i>
          1 Rue xxx, Saint Denis, 97xxx
        </div>
        <div class="item">
          <i class="icon fas fa-phone"></i>
          +2629200000
        </div>
        <div class="item">
          <i class="icon fas fa-envelope"></i>
          autoecole@gmail.ru
        </div>
        <div class="item">
          <i class="icon fas fa-clock"></i>
            <h4> Horaires </h4>
        </div>
            <ul>
              <li> Lundi: 14:00 -18:00 </li>
              <li> De mardi à Vendredi: 08:00-12:00 et  13:00 -18:00 </li>
              <li> Samedi: 08:00-12:00 </li>
            </ul>
      </div>

      <form action="" class="contact-form">
        <input type="text" class="textb" placeholder="Prénom">
        <input type="email" class="textb" placeholder="Votre Email">
        <textarea placeholder="Votre message"></textarea>
        <input type="submit" class="btn" value='Envoyer'>
      </form>
      <br><br>

      <%= link_to "Devenir Professeur", new_user_registration_path(type: 'teacher') %>

    </div>
  </div>
</html>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AutoEcole</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application' %>
    <link href="../assets/stylesheets/styles.css" rel="stylesheet" />
    <link href= "../assets/stylesheets/home.scss">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <body>
    <div class="landing_pg">
      <header>
        <div class="logo">
          <%= link_to "Auto Ecole Alpha", home_path %>
        </div>
        <nav>
          <div class="sub-menu">
            <%= link_to "Accueil", accueille_path%>
            <%= link_to "Permis Auto", permis_auto_path %>
            <%= link_to "Le Code en ligne", home_path %>
            <% if user_signed_in? %>
              <% if current_user.teacher != nil %>
                <%= link_to "Profil Professeur", teacher_show_path %>
              <% elsif current_user.admin != true %>
                <%= link_to "Mon Profile", student_show_path %>
              <% elsif current_user.admin == true%>
                <%= link_to "Profile Admin", admin_students_path %>
              <% end %>
            <% else %>
              <%= link_to "Mon Profile", new_user_session_path %>
            <% end %>
            <%=link_to "Calendrier", calendar_index_path %>
            <%=link_to "Contact", contact_path %>
          </div>
        </nav>
      </header>

      <div class="content">
        <div class="catch-phrase">
          <h1> Here we can logo <br><span>Or we can use catch-phrase!</span></h2>
          <br>
          <h5><b> Some small explenations or some phrase, description, mostly 3 lines phrases no more <br>
            no more mostly 3 lines phrases no more,mostly 3 lines phrases no more</b>
          </h5>
          <br>
        </div>

        <div class="inline">
          <%= link_to  "Se connecter", user_session_path, class: "info-btn" %>
          <br><br>
          <%= link_to  "S'INSCRIRE", new_user_registration_path, class: "info-btn" %>
        </div>
      </div>

      <div class="social-media-icones">
        <span>
          <a href="#" class="fa fa-facebook"></a>
        </span>
        <span>
          <a href="#"><i class="fa fa-twitter"></i></a>
        </span>
        <span>
          <a href="#"><i class="fa fa-instagram"></i></a>
        </span>
        <span>
          <a href="#"><i class="fa fa-twitch"></i></a>
        </span>
      </div>
    </div>
    <br>
  </body>

app/views/static_pages/permis_auto.html.erb
<!DOCTYPE html>
<body>

<div style="width: 400px; margin: 0 auto; padding-top: 30px; padding-bottom: 50px;">
  <div class="testimonial-quote group">
    <div class="quote-container">
      <blockquote>
        <p>Nos offres pour le permis Auto!</p>
      </blockquote>
    </div>
  </div>
</div>

<div class="wrapper3">
  <div class="wrapper3-item">
    <div class="card">
      <div class="title">
        <label> FORMATION B </label>
      </div>
      <%= image_tag "img1.jpg", height: 200, width: '449' %>
      <div class="text-grid">
        <div class="text-on-grid">
          <p> Dévoiler les options</p>
        </div>
        <button type="button" class="question-btn">
          <span class="plus-icon">
            <i class="far fa-plus-square"></i>
          </span>
          <span class="minus-icon">
            <i class="far fa-minus-square"></i>
          </span>
        </button>
      </div>
      <div class="question-text">
        <div class="text-grid">
          <div class="text-on-grid">
            <p> DEMARCHE ADMINISTRATIVES</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 50 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> COURS COLLECTIFS ET PROJECTIONS EN SALLE</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 130 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> LIVRE DE CODE</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 20 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> CLASSE ROUSSEAU</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 20 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> 1 Heure d'évaluation de conduite</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 40 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> 1 Heure de conduite individuel effectif au volant</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 40 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Kit Pedagogique (fiche de suivi + fiche d'évalution + livret d'apprentissage) d'évaluation de conduite</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 20 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Livre de vérification</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 20 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Premier Prestation à l'examen pratique</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 0 €</p>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="wrapper3-item">
    <div class="card">
      <div class="title">
        <label> FORMATION AAC </label>
      </div>
      <%= image_tag "img2.jpg", height: 200, width: 449 %>
      <div class="text-grid">
        <div class="text-on-grid">
          <p> Dévoiler les options</p>
        </div>
        <button type="button" class="question-btn">
          <span class="plus-icon">
            <i class="far fa-plus-square"></i>
          </span>
          <span class="minus-icon">
            <i class="far fa-minus-square"></i>
          </span>
        </button>
      </div>
      <div class="question-text">
        <div class="text-grid">
          <div class="text-on-grid">
            <p> DEMARCHE ADMINISTRATIVES</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 50 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> COURS COLLECTIFS ET PROJECTIONS EN SALLE</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 130 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> LIVRE DE CODE</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 20 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> CLASSE ROUSSEAU</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 20 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> 1 Heure d'évaluation de conduite</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 40 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> 1 Heure de conduite individuel effectif au volant</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 40 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Kit Pedagogique (fiche de suivi + fiche d'évalution + livret d'apprentissage) d'évaluation de conduite</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 20 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Livre de vérification</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 20 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Rendez-vous préalable</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 45 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Rendez-vous pédagogique 1</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 45 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Rendez-vous pédagogique 2</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 45 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Premier Prestation à l'examen pratique</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 0 €</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="wrapper3-item">
    <div class="card">
      <div class="title">
        <label> PRESTATIONS HORS FORMULES </label>
      </div>
      <%= image_tag "img3.png", height: 200, width: 460 %>
      <div class="text-grid">
        <div class="text-on-grid">
          <p> Dévoiler les options</p>
        </div>
        <button type="button" class="question-btn">
          <span class="plus-icon">
            <i class="far fa-plus-square"></i>
          </span>
          <span class="minus-icon">
            <i class="far fa-minus-square"></i>
          </span>
        </button>
      </div>
      <div class="question-text">
        <div class="text-grid">
          <div class="text-on-grid">
            <p> 1 HEURE D'EVALUATION</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 40 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> 1 HEURE DE LEÇON DE CONDUITE</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 40 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> 1 HEURE DE LEÇON DE CONDUITE BOITE AUTO</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 42 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> RENDEZ VOUS PREALABLE/PEDAGOGIQUE 1 ET 2</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 45 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Transfert de dossier</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 100 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Livre de vérification</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 20 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Passe Rousseau</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 50 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Renouvellement</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 30 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Kit Pedagogique (fiche de suivi + fiche d'évalution + livret d'apprentissage)</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 60 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Frais d'éxamen</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 40 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Frais de gestion du dossier</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 100 €</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="wrapper3-item">
    <div class="card">
      <div class="title">
        <label> FORMATION BOITE AUTO </label>
      </div>
      <%= image_tag "img3.png", height: 200, width: 460 %>
      <div class="text-grid">
        <div class="text-on-grid">
          <p> Dévoiler les options</p>
        </div>
        <button type="button" class="question-btn">
          <span class="plus-icon">
            <i class="far fa-plus-square"></i>
          </span>
          <span class="minus-icon">
            <i class="far fa-minus-square"></i>
          </span>
        </button>
      </div>
      <div class="question-text">
        <div class="text-grid">
          <div class="text-on-grid">
            <p> 1 HEURE D'EVALUATION</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 42 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> 1 HEURE DE LEÇON DE CONDUITE</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 42 €</p>
          </div>
        </div>
        <div class="text-grid">
          <div class="text-on-grid">
            <p> Frais d'éxamen</p>
          </div>
          <div class="text-on-grid">
            <p style="text-align:right"> 42 €</p>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
<br><hr><br>

  <script>
    const btns=document.querySelectorAll('.question-btn');

    btns.forEach(function(btn){
      btn.addEventListener("click",function(e){
        const question=e.currentTarget.parentElement.
        parentElement;
        question.classList.toggle("show-text");
        });
    });
  </script>

</body>

app/views/static_pages/permis_moto.html.erb
<!DOCTYPE html>

<div style="width: 400px; margin: 0 auto; padding-top: 30px; padding-bottom: 50px;">
  <div class="testimonial-quote group">
    <div class="quote-container">
      <blockquote>
        <p>Nos offres pour le permis Moto!</p>
      </blockquote>
    </div>
  </div>
</div>

<div class="wrapper3">
  <div class="card">
    <div class="wrapper3-item">
      <div class="title">
        <label> Moto 1 </label>
      </div>
      <%= image_tag "moto1.jpg", height: 200 %>
      <p>All the Lorem Ipsum generators on the. Internet tend to repeat predefined chunks as necessary</p>
    </div>
  </div>

  <div class="card">
    <div class="wrapper3-item">
      <div class="title">
        <label> Moto 2 </label>
      </div>
      <%= image_tag "moto2.jpg", height: 200 %>
      <p>All the Lorem Ipsum generators on the. Internet tend to repeat predefined chunks as necessary</p>
    </div>
  </div>

  <div class="card">
    <div class="wrapper3-item">
      <div class="title">
        <label> Moto 3 </label>
      </div>
      <%= image_tag "moto3.jpg", height: 200, width: 300 %>
      <p>All the Lorem Ipsum generators on the. Internet tend to repeat predefined chunks as necessary</p>
    </div>
  </div>
</div>

<br><hr><br>

app/views/static_pages/provisoir.html.erb
<h4> Sign out pour le professeur</h4>
<%= link_to "Log out", destroy_teacher_session_path, method: :delete %>