config/routes.rb
Rails.application.routes.draw do

  get 'timeslots/index'
  get 'timeslots/new'
  post 'timeslots/create'
  get 'teacher/index'
  get 'teacher/show'
  get 'teacher/new'
  get 'student/index'
  get 'student/show'
  get 'admin/show'
  namespace :admin do
    resources :students, only: [:new, :edit, :create, :destroy, :update, :index]
    resources :calendar, only: [:new, :edit, :create, :destroy, :update]
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :static_pages
  root to: "static_pages#home"

  resources :lesson, only: [:create, :destroy]
  resources :calendar, only: [:index, :create, :new, :show]
  get 'home', to: 'static_pages#home'
  get 'accueille', to: 'static_pages#accueille'
  get 'permis_auto', to: 'static_pages#permis_auto'
  get 'permis_moto', to: 'static_pages#permis_moto'
  get 'contact', to: 'static_pages#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_many :timeslots
  belongs_to :teacher

  accepts_nested_attributes_for :timeslots
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :student
  belongs_to :timeslot
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :lessons

  has_many :timeslots, through: :lessons
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :calendars
  has_many :timeslots
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  belongs_to :teacher
  belongs_to :calendar
  has_many :time_slots
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_one :student
  has_one :teacher

  accepts_nested_attributes_for :student
  accepts_nested_attributes_for :teacher
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  #before_action :configure_sign_up_params, if: :devise_controller?

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_action :check_teacher, except: [:index, :show]

  def index
    @calendar_all = Calendar.where("reference_day >= ?", Date.today)
  end

  def show
    @lessons = Lesson.all
    @calendar_selected = Calendar.find(params[:id])
  end

  def new
    @calendar = Calendar.new
  end

  def create
    (0..end_date_loop).each do |i|
      iterated_day = start_date_selected + i
      calendar = Calendar.new(:teacher_id => current_user.teacher.id,
      :reference_day => iterated_day)
      calendar.save
    end
    redirect_to calendar_index_path
  end

  private
  def check_teacher
    unless current_user.teacher != nil || current_user.admin == true
      redirect_to '/', :alert => "Don't have permission!"
    end
  end

  def end_date_loop
    (end_date_selected - start_date_selected).to_i
  end

  def start_date_selected
    Date.strptime(custom_params.values[0..2].join('-'), "%d-%m-%Y")
  end

  def end_date_selected
    Date.strptime(custom_params.values[3..5].join('-'), "%d-%m-%Y")
  end

  def custom_params
    params.require(:calendar).permit(:start_date, :end_date)
  end

end

app/controllers/lesson_controller.rb
class LessonController < ApplicationController

  def show
  end

  def create
    create_lesson = Lesson.new(student_id: current_user.student.id, timeslot_id: params[:timeslot_id])
    if current_user.student.credits == nil || current_user.student.credits < 1
      flash[:erreur] = "Erreur, vous n'avez pas assez des credits pour le créneau !"
      redirect_to calendar_index_path
    elsif create_lesson.save
      current_user.student.update({credits: current_user.student.credits-1})
      redirect_to student_show_path
    else
      flash["error"] = "Vous n'avez pas crée la lesson"
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    if @lesson.destroy
      current_user.student.update({credits: current_user.student.credits+1})
      redirect_to student_show_path
    end
  end

  private

end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :configure_sign_up_params, only: [:create]
  before_action :check_student, except: [:index]

  def index
    @students = Student.all
  end

  def show
    @current_student = current_user.student
    @lesson = Lesson.where(student_id: current_user.student.id)
  end

  private
  def check_student
    unless current_user.student || current_user.admin == true
        redirect_to '/', :alert => "Don't have permission!"
    end
  end

end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController

  def show
    @current_teacher = current_user.teacher
  end

end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  before_action :check_teacher, except: [:index]

  def index
    @time_slots_all = Timeslot.all
    @calendar_week_day = Calendar.all
    #Timeslot.find(:all, :conditions => [@time_slots_all.start_slot < Time.now])
  end

  def new
    @time_slots = Timeslot.new
  end

  def create
      Calendar.all.each do |calendar|
      day = calendar.reference_day.strftime('%A')
      if day == "Monday"
        (0..length1).each do |x|
          final_slots = Timeslot.new(teacher_id: current_user.teacher.id,
          start_slot: looping_slots(morning_start + (4 * 3600 ))[x],
          end_slot: looping_slots(morning_start + (5 * 3600))[x],
          calendar_id: calendar.id
          )
          final_slots.save
        end
      elsif day == "Tuesday" || day == "Wednesday" || day == "Friday" || day == "Thursday"
        (0..length2).each do |x|
          final_slots = Timeslot.new(teacher_id: current_user.teacher.id,
          start_slot: loop_full_day(morning_start)[x],
          end_slot: loop_full_day(morning_start + 3600)[x],
          calendar_id: calendar.id
          )
          final_slots.save
        end
      elsif day == "Saturday"
        (0..length1).each do |x|
          final_slots = Timeslot.new(teacher_id: current_user.teacher.id,
          start_slot: looping_slots(morning_start)[x],
          end_slot: looping_slots(morning_start + 3600)[x],
          calendar_id: calendar.id
          )
          final_slots.save
        end
      end
    end
  end

  private
  def check_teacher
    unless current_user.teacher
        redirect_to '/', :alert => "Don't have permission!"
    end
  end

  def length1
    looping_slots(morning_start + (4 * 3600)).length - 1
  end

  def length2
    loop_full_day(morning_start).length - 1
  end

  def looping_slots(slot)
    (0..4).map do |i|
      (slot + i * 3600).hour.to_s
    end
  end

  def loop_full_day(slot)
    [0,1,2,3,4,6,7,8,9].map do |i|
      (slot + (i * 3600)).hour.to_s
    end
  end

  def morning_start
    Time.parse("08:00")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lesson_helper.rb
module LessonHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/teacher_student_helper.rb
module TeacherStudentHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/calendar/index.html.erb
<h2 style>Calendrier, Selectionez votre jour </h2>

<div class="wrapper-calendar">
  <% @calendar_all.each do |date| %>
    <%= link_to calendar_path(date.id) do %>
      <div class="calendar-cell">
        <ul>
          <h5><%= date.reference_day.strftime('%A, %d - %B') %></h5>
        </ul>
        <% if date.reference_day.strftime('%A') == "Sunday" %>
          <h6> Fermé!<br> Pas de cours </h6>
        <% else %>
          <% date.timeslots.map do |time_slot| %>
            <%#= link_to lesson_index_path(timeslot_id: time_slot.id), method: :post do %>
              <%= time_slot.start_slot %>:00 -
              <%= time_slot.end_slot %>:00<br>
            <%# end %>
          <% end %><br>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/calendar/new.html.erb
<h3> Création de calendrier</h3>

<%= form_with(model: @calendar, url: calendar_index_path) do |f| %>

  <div class="form-group">
    <label> Choisissez le premier jour du calendrier</label>
    <%= f.date_select :start_date, :order => [:day, :month, :year] %><br>
    <label> Choisissez le dernièr jour du calendrier</label>
    <%= f.date_select :end_date, :order => [:day, :month, :year] %><br>
    <%= f.submit "Créer les jours" %>
  </div>

<% end %>

app/views/calendar/show.html.erb
<div class="calendar-cell">

  <ul>
    <h5><%= @calendar_selected.reference_day.strftime('%A, %d - %B') %></h5>
  </ul>

  <% @calendar_selected.timeslots.map do |time_slot| %>
    <% if @lessons.detect {|lesson| lesson.timeslot_id == time_slot.id} %>
        <p> Cours réservé<br/>
          <%= time_slot.start_slot %>:00 -
          <%= time_slot.end_slot %>:00<br>
        </p>
      <% else %>
        <%= link_to lesson_index_path(timeslot_id: time_slot.id), method: :post do %>
        <%= time_slot.start_slot %>:00 -
        <%= time_slot.end_slot %>:00<br>
      <% end %>
    <% end %>
  <% end %><br/>

</div><br/>

app/views/lesson/create.html.erb
<h1>Lesson#create</h1>

<%= form_with(model: lesson) do |f| %>
  <div class="field">
    <%= f.label "Remarque 1" %>
    <%= f.text_field :remark1 %>
    <br>
  </div>

  <div class="field">
    <%= f.label "Remarque 2" %>
    <%= f.text_field :remark2 %>
    <br>
  </div>

  <div class="field">
    <%= f.label "Remarque 3" %>
    <%= f.text_field :remark3 %>
    <br>
  </div>

  <div class="field">
    <%= f.label "Remarque 4" %>
    <%= f.text_field :remark4 %>
    <br>
  </div>


<% end %>

app/views/lesson/index.html.erb
<h1>Lesson#index</h1>

<p>Find me in app/views/lesson/index.html.erb</p>

app/views/lesson/new.html.erb
<%= form_with(model: @lesson, url: lesson_create_path) do |f| %>

  <label> Date du cours </label>
    <div class="field">
      <%= f.date_field :date %>
      <br><br>
    </div>

  <label> Début du cours </label>
    <div class="field">
      <%= f.time_field :start_lesson, :format=>"%H:%M" %>
      <br><br>
    </div>

  <label> Fin du cours </label>
    <div class="field">
      <%= f.time_field :end_lesson, :format=>"%H:%M" %>
      <br><br>
  </div>


  <%= f.label "évaluation/rémarque individuel" %>
    <div class="field">
      <%= f.text_field :remark1 %>
      <br><br>
    </div>

  <div class="form-group">
    <%= f.submit "Create", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/lesson/show.html.erb
<h1>Lesson#show</h1>
<p>Find me in app/views/lesson/show.html.erb</p>

app/views/teacher/create.html.erb
<h1>Teacher#create</h1>
<p>Find me in app/views/teacher/create.html.erb</p>

app/views/teacher/index.html.erb
<h1>Teacher#index</h1>
<p>Find me in app/views/teacher/index.html.erb</p>

app/views/teacher/new.html.erb
<h1>Teacher#new</h1>
<p>Find me in app/views/teacher/new.html.erb</p>

app/views/teacher/show.html.erb
<h1>Teacher#show</h1>
<p>Find me in app/views/teacher/show.html.erb</p>

<h4> Bienvenue Monsieur:
<%= @current_teacher.first_name %>
<%= @current_teacher.last_name %></h4><br/>
<h5> Si vous voulez créer un caldndrier:
cliquez ici: <%= link_to "Calendrier", new_calendar_path %><br/>
Et si vous voulez lancer les créneaux: <%= link_to "Crénaux", timeslots_new_path %>
</h5>

app/views/timeslots/create.html.erb
<h1>Timeslots#create</h1>
<p>Find me in app/views/timeslots/create.html.erb</p>

app/views/timeslots/index.html.erb
<h1>Timeslots#index</h1>

<%= @timeslot_selected_id %>

<% @time_slots_all.each do |time_slots| %>
  <ul>
    <li><p><%= time_slots.calendar.reference_day.strftime('%A') %>, le
    <%= time_slots.calendar.reference_day %></li>
    <li><p> La conduite avec monsieur
    <%= time_slots.teacher.last_name %> commence à <%= time_slots.start_slot %>:00
    heure et ça termine à <%= time_slots.end_slot %>:00 heure</p></li>
    <p> Vous pouvez sélectionner cette conduite!</p> <br>
  </ul>
<% end %>

app/views/timeslots/new.html.erb
<h1>Lancer les créneaux</h1><br/>
<%= form_with(model: @time_slots, url: timeslots_create_path) do |f| %>

  <div class="form-group">
    <%= f.submit "Créer les créneaux" %>
  </div>

  <h4> La Création des créneaux va se faire automatiquement
      selon les horaires officiles de chaque jour </h4><br/><br/>

<% end %>