config/routes.rb
Rails.application.routes.draw do

  get 'timeslots/index'
  get 'timeslots/new'
  post 'timeslots/create'
  get 'teacher/index'
  get 'teacher/show'
  get 'teacher/new'
  get 'student/index'
  get 'student/show'
  get 'admin/show'
  namespace :admin do
    resources :students, only: [:new, :edit, :create, :destroy, :update, :index]
    resources :calendar, only: [:new, :edit, :create, :destroy, :update]
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :static_pages
  root to: "static_pages#home"

  resources :lesson, only: [:create, :destroy]
  resources :calendar, only: [:index, :create, :new, :show]
  get 'home', to: 'static_pages#home'
  get 'accueille', to: 'static_pages#accueille'
  get 'permis_auto', to: 'static_pages#permis_auto'
  get 'permis_moto', to: 'static_pages#permis_moto'
  get 'contact', to: 'static_pages#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_many :timeslots
  belongs_to :teacher

  accepts_nested_attributes_for :timeslots
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :student
  belongs_to :timeslot
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_many :lessons

  has_many :timeslots, through: :lessons
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :user
  has_many :calendars
  has_many :timeslots
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  belongs_to :teacher
  belongs_to :calendar
  has_many :time_slots
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_one :student
  has_one :teacher

  accepts_nested_attributes_for :student
  accepts_nested_attributes_for :teacher
end

app/controllers/admin/students_controller.rb
class Admin::StudentsController < ApplicationController
  before_action :authenticate_admin

  def index
    @list_students = Student.all
  end

  def edit
    @edit_student = Student.find(params[:id])
  end

  def update
    @edit_student = Student.find(params[:id])
    if @edit_student.update(ajoutter_credits)
      flash[:success] = "Les credits ont été ajoutté!"
      redirect_to admin_students_path
    else
      flash[:erreur] = "Credits n'ont pas été ajoutté!"
      render 'edit'
    end
  end

  private
  def ajoutter_credits
    params.require(:student).permit(:credits)
  end

  def authenticate_admin
    unless current_user&.admin
      flash[:erreur] = "Vous n'êtes pas administrateur"
      redirect_to root_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  #before_action :configure_sign_up_params, if: :devise_controller?

end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_action :check_teacher, except: [:index, :show]

  def index
    @calendar_all = Calendar.where("reference_day >= ?", Date.today)
  end

  def show
    @lessons = Lesson.all
    @calendar_selected = Calendar.find(params[:id])
  end

  def new
    @calendar = Calendar.new
  end

  def create
    (0..end_date_loop).each do |i|
      iterated_day = start_date_selected + i
      calendar = Calendar.new(:teacher_id => current_user.teacher.id,
      :reference_day => iterated_day)
      calendar.save
    end
    redirect_to calendar_index_path
  end

  private
  def check_teacher
    unless current_user.teacher != nil || current_user.admin == true
      redirect_to '/', :alert => "Don't have permission!"
    end
  end

  def end_date_loop
    (end_date_selected - start_date_selected).to_i
  end

  def start_date_selected
    Date.strptime(custom_params.values[0..2].join('-'), "%d-%m-%Y")
  end

  def end_date_selected
    Date.strptime(custom_params.values[3..5].join('-'), "%d-%m-%Y")
  end

  def custom_params
    params.require(:calendar).permit(:start_date, :end_date)
  end

end

app/controllers/lesson_controller.rb
class LessonController < ApplicationController

  def show
  end

  def create
    create_lesson = Lesson.new(student_id: current_user.student.id, timeslot_id: params[:timeslot_id])
    if current_user.student.credits == nil || current_user.student.credits < 1
      flash[:erreur] = "Erreur, vous n'avez pas assez des credits pour le créneau !"
      redirect_to calendar_index_path
    elsif create_lesson.save
      current_user.student.update({credits: current_user.student.credits-1})
      redirect_to student_show_path
    else
      flash["error"] = "Vous n'avez pas crée la lesson"
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    if @lesson.destroy
      current_user.student.update({credits: current_user.student.credits+1})
      redirect_to student_show_path
    end
  end

  private

end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :configure_sign_up_params, only: [:create]
  before_action :check_student, except: [:index]

  def index
    @students = Student.all
  end

  def show
    @current_student = current_user.student
    @lesson = Lesson.where(student_id: current_user.student.id)
  end

  private
  def check_student
    unless current_user.student || current_user.admin == true
        redirect_to '/', :alert => "Don't have permission!"
    end
  end

end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController

  def show
    @current_teacher = current_user.teacher
  end

end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  before_action :check_teacher, except: [:index]

  def index
    @time_slots_all = Timeslot.all
    @calendar_week_day = Calendar.all
    #Timeslot.find(:all, :conditions => [@time_slots_all.start_slot < Time.now])
  end

  def new
    @time_slots = Timeslot.new
  end

  def create
      Calendar.all.each do |calendar|
      day = calendar.reference_day.strftime('%A')
      if day == "Monday"
        (0..length1).each do |x|
          final_slots = Timeslot.new(teacher_id: current_user.teacher.id,
          start_slot: looping_slots(morning_start + (4 * 3600 ))[x],
          end_slot: looping_slots(morning_start + (5 * 3600))[x],
          calendar_id: calendar.id
          )
          final_slots.save
        end
      elsif day == "Tuesday" || day == "Wednesday" || day == "Friday" || day == "Thursday"
        (0..length2).each do |x|
          final_slots = Timeslot.new(teacher_id: current_user.teacher.id,
          start_slot: loop_full_day(morning_start)[x],
          end_slot: loop_full_day(morning_start + 3600)[x],
          calendar_id: calendar.id
          )
          final_slots.save
        end
      elsif day == "Saturday"
        (0..length1).each do |x|
          final_slots = Timeslot.new(teacher_id: current_user.teacher.id,
          start_slot: looping_slots(morning_start)[x],
          end_slot: looping_slots(morning_start + 3600)[x],
          calendar_id: calendar.id
          )
          final_slots.save
        end
      end
    end
  end

  private
  def check_teacher
    unless current_user.teacher
        redirect_to '/', :alert => "Don't have permission!"
    end
  end

  def length1
    looping_slots(morning_start + (4 * 3600)).length - 1
  end

  def length2
    loop_full_day(morning_start).length - 1
  end

  def looping_slots(slot)
    (0..4).map do |i|
      (slot + i * 3600).hour.to_s
    end
  end

  def loop_full_day(slot)
    [0,1,2,3,4,6,7,8,9].map do |i|
      (slot + (i * 3600)).hour.to_s
    end
  end

  def morning_start
    Time.parse("08:00")
  end

end

app/helpers/admin/students_helper.rb
module Admin::StudentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lesson_helper.rb
module LessonHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/teacher_student_helper.rb
module TeacherStudentHelper
end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/admin/students/edit.html.erb
<h3> Ajoutter des credits à mensieur
  <%= @edit_student.last_name %> <%= @edit_student.first_name %> </h3>

<%= form_with model:[:admin, @edit_student] do |f| %>
  <p>Number de credits que vous voulez ajouter</p>
  <%= f.number_field :credits %><br><br>
  <%= f.submit 'Ajouter les credits' %><br><br>
<% end %>

app/views/admin/students/index.html.erb
<h3> Tous les utilisateurs </h3>

<h4> Création de nouveau dates dans le calendrie:
<%= link_to "Créer nouveaux dates", new_calendar_path %><br/></h4>
<h4> Création de créneaux:
<%= link_to "Créer des créneaux", timeslots_new_path %><br/></h4><br/><br/>
<p>_____________________________________________________________
_________________________________________________________</p>
<% @list_students.each do |student|%>
  <p> Le nom de l'étudiant
    <%= student.first_name %>
  </p>

  <p> Le prénom de l'étudiant
    <%= student.last_name %>
  </p>

  <p> Actuelement il possede
    <%= student.credits %> credits
  </p>

  <%= link_to "Ajoutter des credits", edit_admin_student_path(student.id) %> <br><br>
<% end %>

app/views/student/create.html.erb
<h1>Student#create</h1>
<p>Find me in app/views/student/create.html.erb</p>

app/views/student/index.html.erb
<h1>Students</h1>
<% @students.map do |student|%>
  <%= student.first_name %><br/>
  <%= student.last_name %><br/><br/>
<% end %>

app/views/student/new.html.erb
<h1>Student#index</h1>
<p>Find me in app/views/student/index.html.erb</p>

app/views/student/show.html.erb
<h1>Votre Profil</h1><br><br>
<p> Bienvenue monsieur
  <%= @current_student.first_name %>
  <%= @current_student.last_name %><br>
  Vous avez: <%= @current_student.credits %> credits
</p>
<p> Vos cours sont:<br>
__________________________<br>
  <% @lesson.each_with_index do |lesson, i| %>
    <%= lesson.timeslot.calendar.reference_day.strftime('%A-%D') %><br/>
    cours <%= i+1 %>:
    <%= lesson.timeslot.start_slot %>:00-
    <%= lesson.timeslot.end_slot %>:00<br/>
    <%= lesson.timeslot.calendar.reference_day %><br/>
    <% if  Date.today + 2  <=  lesson.timeslot.calendar.reference_day %><br/>
      <%= link_to "Supprimer le cours", lesson, method: :delete, data: { confirm: 'Êtes vous sûr de supprimer?' } %><br/><br/>
    <% else %>
      <p style="color: #FF0000";> Vous ne pouvez plus supprimer le cours que vous avez reservé </p>
    <% end %>
  <% end %>
__________________________<br>
</p>

<p> Si vous voulez voir les heures de cours disponibles
  <%= link_to "Calendrier", calendar_index_path %>
</p>